install.packages('rattle')
install.packages('rpart.plot')
install.packages('RColorBrewer')
install.packages('rpart')
install.packages('RODBC')
library(rattle)
library(rpart.plot)
library(RColorBrewer)
library(rpart)
library(Hmisc)
library(MASS)
library(relaimpo)
library(corrplot)

dat <- read.csv('C:/Users/vshah/Documents/book41.csv' , sep=",")
describe(dat)
cor(dat,method="spearman" )
cor.test( dat[,17], dat[,18])
#model = lm(Total.Sales ~ Product.Page.Views  * Impressions + Total.SKUs + SourceA + SourceB + SourceC + FreeShip +Avg.Price * Avg.Shipping.Price + Missing.Images + New.Customer.Reviews + Customer.count  + Customer.Views , data = dat )
model = lm(Total.Sales ~ Product.Page.Views    + New.Customer.Reviews  , data = dat )
summary(model)
model1 = lm(Total.Sales ~ SourceA + SourceB   + FreeShip * Avg.Shipping.Price + New.Customer.Reviews + Customer.count * Customer.Views , data = dat )
summary(model1)
model2= lm(Total.Sales ~ + Total.SKUS + Impressions + SourceA + SourceB, data = dat )
summary(model2)
predict(model)
dat$Total.Sales
plot (dat)
summary(dat)
describe(model1)
anova(model1,model)
step <- stepAIC(model, direction="both")
step$anova
calc.relimp(model, type = c("lmg"), rela= TRUE)

model = lm(Total.Sales ~ Product.Page.Views  * Impressions + Total.SKUs  + SourceB + SourceC + FreeShip +Avg.Price * Avg.Shipping.Price + Missing.Images + New.Customer.Reviews + Customer.count  + Customer.Views , data = dat )
summary(model)

model = lm(Total.Sales ~ Impressions+Product.Page.Views+SourceB +SourceA  +Avg.Shipping.Price  , data = dat )
summary(model)
summary(dat)
corrplot(cor(dat),method = "circle")

model1 = lm(Units.count ~  Impressions+Product.Page.Views   + SourceA + SourceB  + Avg.Shipping.Price    , data = dat )
summary(model1)